spring:
  datasource:
    url: jdbc:postgresql://46.101.182.178:26780/glsdemo
    username: postgres
    password: GliesereumAdmin0013
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: ${db.schema}
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/all
    baseline-version: 1
    sql-migration-suffixes: .sql
    sql-migration-prefix: V
    schemas: ${db.schema}

  mail:
    default-encoding: UTF-8
    host: mail.adm.tools
    username: support@gliesereum.com
    password: Support0013
    from: GLIESEREUM<support@gliesereum.com>
    subject: Gliesereum verification mail
    chanel-verification: verificationQueue
    log-email: log@gliesereum.com
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
            trust: "*"

  rabbitmq:
    host: 207.154.239.122
    port: 5672
    password: Af2f4dsASF
    username: rabbit
    connection-timeout: 5s
    queue-logstash-system: logstash-system
    queue-logstash-request: logstash-request

phone:
  acemount:
    url: https://api.acemountmedia.com/sms/
    alpha-name: SECURITY
    token: Bearer shiM8uESwOEAWEurmDWGNmY6LPSy_x1m
  mobizon:
    url: https://api.mobizon.ua/service/
    token: ua6bf786d392ac07d7045f72bc72687e24d80cd08d00e35e4f22736534b1a83b2f3163
  sendSms : false


